---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: guestbook
  name: redis-master-pr
  labels:
    app: redis-master-app
spec:
  clusterSelector:
    matchLabels:
      name: primary

