apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: guestbook-subs
  namespace: guestbook
  labels:
    app: guestbook-app
  annotations:
    apps.open-cluster-management.io/git-path: applications/guestbook-app
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: application-samples/gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: guestbook-pr
...
