---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bdg-app
  namespace: bdg
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - bdg-app
...
