---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/bgd/overlays/pro-ocp
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: bgd-app
  name: bgd-subs
  namespace: bgd
spec:
  channel: application-samples/gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: bgd-pr
  timewindow:
    windowtype: active
    location: "Europe/Madrid"
    daysofweek: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
    hours:
      - start: "12:00AM"
        end: "11:30PM"
...
