---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: guestbook
  name: redis-slave-pr
  labels:
    app: redis-slave-app
spec:
  clusterSelector:
    matchLabels:
      name: secondary
...
