---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: guestbook
  name: redis-slave-subs
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/redis-slave-app
  labels:
    app: redis-slave-app
spec:
  channel: application-samples/gitops
  placement:
    placementRef:
      name: redis-slave-pr
      kind: PlacementRule
...
