---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: applications/pacman-dr
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: pacman-dr
  name: pacman-dr-subscription
  namespace: pacman-dr
spec:
  channel: application-samples/gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-dr-pr
...
